const translations = {
    en: {
        header: {
            title: "Super QR Tool",
            premium: "Premium",
            home: "Home",
            features: "Features",
            pricing: "Pricing",
            contact: "Contact",
            createQR: "Create QR Code",
            lang: "VI"
        },
        tabs: {
            url: "URL",
            text: "Text",
            email: "Email",
            phone: "Phone",
            sms: "SMS",
            wifi: "Wi-Fi",
            vcard: "vCard",
            location: "Location",
            event: "Event",
            crypto: "Crypto",
            app: "App",
            social: "Social"
        },
        bulk: {
            placeholder: "Enter multiple links here. Each link on a new line.\nExample:\nhttps://google.com\nhttps://facebook.com",
            btnGenerate: "Generate Bulk QRs",
            btnZip: "Download ZIP",
            selectAll: "Select All",
            deselectAll: "Deselect All",
            colCheck: "Select",
            colID: "ID",
            colContent: "Content",
            colFormat: "Format",
            colAction: "Action",
            btnPreview: "Preview",
            alertEmpty: "Please enter at least 1 line of data",
            alertSelect: "Please select at least 1 QR code to download",
            alertZipSelect: "Please select at least 1 format to zip",
            zipping: "Zipping..."
        },
        modal: {
            title: "QR Code Settings",
            logo: "Logo",
            border: "Border",
            codePoints: "Code points",
            color: "Color",
            text: "Text",
            otherSettings: "Other settings",
            reset: "Reset",
            close: "Save & Close",
            styleClassic: "Classic Style",
            styleSimple: "Simple Style",
            styleMono: "Black & White",
            codeBackground: "Code Background",
            eyeInColor: "Inner Eye Color",
            eyeOutColor: "Outer Eye Color",
            fontSerif: "Serif Font",
            fontSans: "Sans Font",
            fontBrush: "Brush Font",
            textColor: "Text Color",
            margins: "Margins",
            marginNone: "None",
            margin1: "1 Block",
            margin2: "2 Blocks",
            margin3: "3 Blocks",
            margin4: "4 Blocks",
            correction: "Error Correction",
            resolution: "Resolution",
            dpi72: "72 dpi",
            dpi96: "96 dpi",
            dpi150: "150 dpi",
            dpi300: "300 dpi",
            selectLogo: "Select Logo",
            logoEffect: "Logo Effect",
            selectBorder: "Select the border",
            outlineColor: "Outline color",
            zoom: "Zoom",
            opacity: "Opacity",
            codeEyes: "Code eyes",
            recommendedGallery: "Recommended gallery",
            recommendedColors: "Recommended colors",
            customColors: "Custom colors",
            gradientDirection: "Gradient direction",
            size: "Size",
            font: "Font",
            addText: "Add text",
            textPosition: "Text position",
            solidColor: "Solid color",
            gradientColor: "Gradient color",
            foregroundDiagram: "Foreground diagram",
            vertical: "Vertical",
            horizontal: "Horizontal",
            diagonal: "Diagonal",
            center: "Center",
            codeOutside: "Code outside",
            codeInMiddle: "Code in the middle",
            enterFirstLine: "Enter the first line of text you want to add",
            enterSecondLine: "Please enter the second line of text you want to add",
            clear: "Clear",
            otherSettings: "Other settings",
            textAttributes: "Text attributes",
            logoSettings: "Logo settings",
            backgroundColor: "Background color",
            colorSettings: "Color settings",
            enterFirstLine: "Enter the first line of text you want to add",
            enterSecondLine: "Please enter the second line of text you want to add",
            clear: "Clear",
            otherSettings: "Other settings",
            textAttributes: "Text attributes",
            logoSettings: "Logo settings",
            backgroundColor: "Background color",
            colorSettings: "Color settings",
            applyToCodeEyes: "Apply to the code eyes",
            applyToCodeEyes: "Apply to the code eyes",
            applyToCodeEyes: "Apply to the code eyes",
            format: "Format"
        },
        content: {
            settingBtn: "QR Settings",
            titleWebsite: "Generate QR for Website",
            descWebsite: "Enter URL list (1 URL per line)",
            importExcel: "Or Import from Excel/CSV:",
            btnChooseFile: "Choose File",
            btnDownloadTemplate: "Download Template",
            btnGenerate: "Generate QR Codes"
        },
        footer: {
            totalQR: "Total QR Created",
            totalScans: "Total Scans",
            todayScans: "Today Scans",
            lastUpdated: "Last Updated",
            never: "Never",
            vietqr: "Generate VietQR Transfer Code",
            copyright1: "Designed and developed with ❤️ by Dang Vo.",
            copyright2: "© 2026 Super QR Tool. All rights reserved.",
            disclaimer: "This website is currently under internal testing and is intended for internal use only. Information and features may change without prior notice. While every effort is made to ensure the accuracy of the information provided, no representation or warranty is given that the content is complete, accurate, or up to date. The site owner accepts no liability for any direct or indirect loss or damage arising from the use of this website."
        },
        preview: {
            title: "QR Preview",
            btnDownload: "Download",
            downloadPNG: "Download PNG",
            downloadSVG: "Download SVG",
            downloadHTML: "Download HTML"
        },
        form: {
            titleVCard: "Generate QR for VCard",
            titleText: "Generate QR for Text",
            titleEmail: "Generate QR for Email",
            titleSocial: "Generate QR for Social Media",
            selectNetwork: "Select platform",
            socialLink: "Profile URL / Link",
            socialPhone: "Phone Number",
            titleLocation: "Generate QR for Location",
            latitude: "Latitude (e.g., 37.7749)",
            longitude: "Longitude (e.g., -122.4194)",
            titleEvent: "Generate QR for Event",
            eventName: "Event Name",
            eventStart: "Start Time",
            eventEnd: "End Time",
            eventLocation: "Event Location",
            titleCrypto: "Generate QR for Crypto",
            cryptoCurrency: "Cryptocurrency",
            cryptoAddress: "Wallet Address",
            cryptoAmount: "Amount",
            titleApp: "Generate QR for App Download",
            appStore: "Select Store",
            appLink: "App Store / Play Store Link",
            appHint: "To support both iOS and Android automatically, consider using a smart link service (e.g., Linktree).",
            titleFacebook: "Generate QR for Facebook",
            titleWifi: "Generate QR for Wifi",
            titlePhone: "Generate QR for Phone",
            titleSMS: "Generate QR for SMS",
            firstName: "First Name",
            lastName: "Last Name",
            phone: "Phone Number",
            email: "Email",
            company: "Company",
            jobTitle: "Job Title",
            companyPhone: "Company Phone",
            fax: "Fax",
            companyEmail: "Company Email",
            companyWebsite: "Company Website",
            street: "Street",
            city: "City",
            state: "State",
            country: "Country",
            zipCode: "Zip Code",
            postalCode: "Postal Code",
            enterText: "Enter text",
            emailAddress: "Email Address",
            subject: "Subject",
            body: "Body",
            facebookLink: "Facebook Link",
            wifiName: "Wifi Name",
            wifiPassword: "Wifi Password",
            phoneFormat: "Phone Number (e.g., +84987654321)",
            message: "Message"
        }
    },
    vi: {
        header: {
            title: "Super QR Tool",
            premium: "Premium",
            home: "Trang chủ",
            features: "Tính năng",
            pricing: "Bảng giá",
            contact: "Liên hệ",
            createQR: "Tạo Mã QR",
            lang: "EN"
        },
        tabs: {
            url: "Đường dẫn",
            text: "Văn bản",
            email: "Email",
            phone: "Điện thoại",
            sms: "Tin nhắn",
            wifi: "Wi-Fi",
            vcard: "Danh thiếp",
            location: "Vị trí",
            event: "Sự kiện",
            crypto: "Crypto",
            app: "Ứng dụng",
            social: "Mạng xã hội"
        },
        bulk: {
            placeholder: "Nhập nhiều đường dẫn ở đây. Mỗi đường dẫn nằm trên một dòng mới.\nVí dụ:\nhttps://google.com\nhttps://facebook.com",
            btnGenerate: "Tạo Mã QR Hàng Loạt",
            btnZip: "Tải xuống ZIP hàng loạt",
            selectAll: "Chọn tất cả",
            deselectAll: "Bỏ chọn tất cả",
            colCheck: "Chọn",
            colID: "STT",
            colContent: "Nội dung gốc",
            colFormat: "Định dạng",
            colAction: "Thao tác",
            btnPreview: "Xem",
            alertEmpty: "Vui lòng nhập ít nhất 1 dòng dữ liệu",
            alertSelect: "Vui lòng chọn ít nhất 1 mã QR để tải về",
            alertZipSelect: "Vui lòng chọn ít nhất 1 định dạng để nén",
            zipping: "Đang nén..."
        },
        modal: {
            title: "Cài đặt QR",
            logo: "Logo",
            border: "Khung viền",
            codePoints: "Kiểu mắt",
            color: "Màu sắc",
            text: "Văn bản",
            otherSettings: "Cài đặt khác",
            reset: "Đặt lại",
            close: "Xong & Đóng",
            styleClassic: "Cổ điển",
            styleSimple: "Tối giản",
            styleMono: "Đen trắng",
            codeBackground: "Nền mã QR",
            eyeInColor: "Màu mắt trong",
            eyeOutColor: "Màu mắt ngoài",
            fontSerif: "Phông chữ Serif",
            fontSans: "Phông chữ Sans",
            fontBrush: "Phông nét cọ",
            textColor: "Màu chữ",
            margins: "Lề (Margin)",
            marginNone: "Không lề",
            margin1: "1 Ô",
            margin2: "2 Ô",
            margin3: "3 Ô",
            margin4: "4 Ô",
            correction: "Mức độ sửa lỗi",
            resolution: "Độ phân giải",
            dpi72: "72 dpi",
            dpi96: "96 dpi",
            dpi150: "150 dpi",
            dpi300: "300 dpi",
            selectLogo: "Chọn Logo",
            logoEffect: "Hiệu ứng Logo",
            selectBorder: "Chọn khung viền",
            outlineColor: "Màu viền",
            zoom: "Thu phóng",
            opacity: "Độ mờ",
            codeEyes: "Kiểu mắt QR",
            recommendedGallery: "Thư viện đề xuất",
            recommendedColors: "Màu sắc đề xuất",
            customColors: "Màu sắc tùy chỉnh",
            gradientDirection: "Hướng đổ màu",
            size: "Kích thước",
            font: "Phông chữ",
            addText: "Thêm chữ",
            textPosition: "Vị trí chữ",
            solidColor: "Màu đơn sắc",
            gradientColor: "Đổ màu (Gradient)",
            foregroundDiagram: "Hình nền/Đồ họa",
            vertical: "Dọc",
            horizontal: "Ngang",
            diagonal: "Chéo",
            center: "Tỏa từ tâm",
            codeOutside: "Chữ bên ngoài",
            codeInMiddle: "Chữ ở giữa",
            enterFirstLine: "Nhập dòng chữ đầu tiên bạn muốn thêm",
            enterSecondLine: "Vui lòng nhập dòng chữ thứ hai bạn muốn thêm",
            clear: "Xóa",
            otherSettings: "Cài đặt khác",
            textAttributes: "Thuộc tính văn bản",
            logoSettings: "Cài đặt Logo",
            backgroundColor: "Màu nền",
            colorSettings: "Cài đặt màu sắc",
            enterFirstLine: "Nhập dòng chữ đầu tiên bạn muốn thêm",
            enterSecondLine: "Vui lòng nhập dòng chữ thứ hai bạn muốn thêm",
            clear: "Xóa",
            otherSettings: "Cài đặt khác",
            textAttributes: "Thuộc tính văn bản",
            logoSettings: "Cài đặt Logo",
            backgroundColor: "Màu nền",
            colorSettings: "Cài đặt màu sắc",
            applyToCodeEyes: "Áp dụng cho mắt QR",
            applyToCodeEyes: "Áp dụng cho mắt QR",
            applyToCodeEyes: "Áp dụng cho mắt QR",
            format: "Định dạng"
        },
        content: {
            settingBtn: "Cài đặt QR",
            titleWebsite: "Tạo mã QR cho Website",
            descWebsite: "Nhập danh sách URL (mỗi dòng 1 URL)",
            importExcel: "Hoặc Import từ Excel/CSV:",
            btnChooseFile: "Chọn File",
            btnDownloadTemplate: "Tải file mẫu",
            btnGenerate: "Tạo mã QR"
        },
        footer: {
            totalQR: "Tổng QR Đã Tạo",
            totalScans: "Tổng Lượt Quét",
            todayScans: "Lượt Quét Hôm Nay",
            lastUpdated: "Cập Nhật Lần Cuối",
            never: "Chưa có",
            vietqr: "Tạo mã chuyển khoản VietQR",
            copyright1: "Thiết kế và phát triển với ❤️ bởi Dang Vo.",
            copyright2: "© 2026 Super QR Tool. Mọi quyền được bảo lưu.",
            disclaimer: "Trang web này hiện đang trong giai đoạn thử nghiệm nội bộ và chỉ nhằm phục vụ mục đích sử dụng nội bộ. Thông tin và các chức năng có thể thay đổi mà không cần thông báo trước. Mặc dù chúng tôi luôn cố gắng bảo đảm độ chính xác của thông tin được cung cấp, chúng tôi không đưa ra bất kỳ cam kết hay bảo đảm nào rằng nội dung luôn đầy đủ, chính xác hoặc được cập nhật kịp thời. Chủ sở hữu trang web không chịu trách nhiệm đối với bất kỳ tổn thất hoặc thiệt hại trực tiếp hay gián tiếp nào phát sinh từ việc sử dụng trang web này."
        },
        preview: {
            title: "Bản xem trước",
            btnDownload: "Tải xuống",
            downloadPNG: "Tải PNG",
            downloadSVG: "Tải SVG",
            downloadHTML: "Tải HTML"
        },
        form: {
            titleVCard: "Tạo mã QR cho VCard",
            titleText: "Tạo mã QR cho Văn bản",
            titleEmail: "Tạo mã QR cho Email",
            titleSocial: "Tạo mã QR cho Mạng xã hội",
            selectNetwork: "Chọn nền tảng",
            socialLink: "Đường dẫn trang / Kênh",
            socialPhone: "Số điện thoại",
            titleLocation: "Tạo mã QR cho Vị trí GPS",
            latitude: "Vĩ độ (VD: 21.0285)",
            longitude: "Kinh độ (VD: 105.8542)",
            titleEvent: "Tạo mã QR cho Sự kiện",
            eventName: "Tên sự kiện",
            eventStart: "Thời gian bắt đầu",
            eventEnd: "Thời gian kết thúc",
            eventLocation: "Địa điểm tổ chức",
            titleCrypto: "Tạo mã QR Nhận Tiền điện tử",
            cryptoCurrency: "Loại tiền",
            cryptoAddress: "Địa chỉ Ví",
            cryptoAmount: "Số lượng",
            titleApp: "Tạo mã QR Tải ứng dụng",
            appStore: "Chọn chợ ứng dụng",
            appLink: "Đường dẫn tải App",
            appHint: "Do mã QR tĩnh chỉ chứa được 1 đường dẫn, để 1 mã quét được cả 2 HĐH, bạn nên dùng dịch vụ tạo Smart Link.",
            titleFacebook: "Tạo mã QR cho Facebook",
            titleWifi: "Tạo mã QR cho Wifi",
            titlePhone: "Tạo mã QR cho Điện thoại",
            titleSMS: "Tạo mã QR cho Tin nhắn",
            firstName: "Tên",
            lastName: "Họ",
            phone: "Số điện thoại",
            email: "Email",
            company: "Công ty",
            jobTitle: "Chức danh",
            companyPhone: "SĐT Công ty",
            fax: "Fax",
            companyEmail: "Email Công ty",
            companyWebsite: "Website Công ty",
            street: "Đường/Phố",
            city: "Thành phố",
            state: "Tỉnh/Bang",
            country: "Quốc gia",
            zipCode: "Mã Zip",
            postalCode: "Mã bưu chính",
            enterText: "Nhập văn bản",
            emailAddress: "Địa chỉ Email",
            subject: "Tiêu đề",
            body: "Nội dung",
            facebookLink: "Link Facebook",
            wifiName: "Tên Wifi",
            wifiPassword: "Mật khẩu Wifi",
            phoneFormat: "Số ĐT (VD: +84987654321)",
            message: "Nội dung tin nhắn"
        }
    }
};

window.i18n = {
    locale: localStorage.getItem('qr_lang') || 'en',
    t(key) {
        let keys = key.split('.');
        let val = translations[this.locale] || translations['en'];
        for (let k of keys) {
            val = val ? val[k] : null;
        }
        return val || key;
    },
    toggle() {
        this.locale = this.locale === 'en' ? 'vi' : 'en';
        localStorage.setItem('qr_lang', this.locale);
        if (window.vm) {
            window.vm.$forceUpdate();
        }
        if (typeof updateStaticText === 'function') {
            updateStaticText();
        }
    }
};
